const arduinoCardContent = [
    {
        keywords: "Arduino, Conexión, LED, externo, Microcontrolador, Ley, de, Ohm, Resistencia, Circuito, Proyecto, Guía, conexión, Componentes, electrónicos, Tutorial, Polaridad, Valor, Práctica, practica, Construcción, de circuitos",
        title: "Luz a la Obra: Conectando tu Primer LED Externo al Microcontrolador",
        description: "Aventúrate en el práctico aprendizaje de conectar un LED externo a tu microcontrolador en esta entrada. Cubriremos la aplicación de la Ley de Ohm, la selección de la resistencia adecuada y los pasos detallados para crear un circuito luminoso. ",
        imageUrl: "/arduino/luz-a-la-obra-conectando-tu-primer-led-externo-al-microcontrolador/images/Encender-LED-Externo-Arduino.webp",
        imageAlt: "Mano conectando un LED externo a una placa Arduino y probando su funcionamiento",
        link: "/arduino/luz-a-la-obra-conectando-tu-primer-led-externo-al-microcontrolador/",
    },
    {
        keywords: "Arduino, LED, parpadeo, digitalRead, digitalWrite, setup, loop, pinMode, INPUT, OUTPUT, HIGH, LOW, delay, función, código, Tinkercad, simulación, proyecto Arduino, microcontrolador",
        title: "Un Guiño Luminoso: Aprendiendo a Hacer Parpadear un LED con Arduino",
        description: "En esta entrada, damos nuestros primeros pasos haciendo parpadear un LED. Es simple, divertido y el comienzo de un fascinante viaje. ¡Acompáñame!",
        imageUrl: "/arduino/un-guino-luminoso-aprendiendo-a-hacer-parpadear-un-led-con-arduino/images/encender-led-incorporado.webp",
        imageAlt: "LED encendido junto a una placa Arduino",
        link: "/arduino/un-guino-luminoso-aprendiendo-a-hacer-parpadear-un-led-con-arduino/",
    },
    {
        keywords: "Arduino, uno, hardware, pines, digitales, analógicos, microcontrolador, de, alimentación, regulador, voltaje, puertos, comunicación, botón, reset, Puerto,  USB, Voltaje, Input, Vin, Entrada, componentes",
        title: "Explorando el Corazón de Arduino: Un Recorrido por sus Componentes Esenciales",
        description: "¡Da tus primeros pasos en el emocionante mundo de la electrónica y la programación! Explora los componentes esenciales, aprende sobre los pines digitales y analógicos, y abre un mundo lleno de posibilidades.",
        imageUrl: "/arduino/explorando-el-corazon-de-arduino-un-recorrido-por-sus-componentes-esenciales/images/Componentes-Placa-Arduino-UNO.webp",
        imageAlt: "Joven creando un proyecto con la placa Arduino UNO",
        link: "/arduino/explorando-el-corazon-de-arduino-un-recorrido-por-sus-componentes-esenciales/",
    },
    {
        keywords: "arduino, tinkercad, ide, software, interfaz, programacion, proyectos, arduino, entorno, de, trabajo, entorno de trabajo, virtual, placa, codigo, electronica, microcontrolador, entrada, tutorial",
        title: "Iniciando con Arduino: Preparación del Entorno y Plataformas",
        description: "Descubre cómo preparar tu entorno de trabajo en Arduino con esta guía introductoria. Desde plataformas virtuales hasta primeros pasos con el IDE.",
        imageUrl: "/arduino/iniciando-con-arduino-preparacion-del-entorno-y-plataformas/images/muchacho-trabajando-robot-arduino.webp",
        imageAlt: "Imagen de un joven trabajando en la construcción y programación de un robot utilizando Arduino.",
        link: "/arduino/iniciando-con-arduino-preparacion-del-entorno-y-plataformas/",
    },
    {
        keywords: "arduino, introduccion, introduccion a arduino creación, electronica, placas, desarrollo, programacion, proyectos, comunidad",
        title: "Arduino: Sumérgete en el Universo de la Creación Electrónica",
        description: "Descubre el fascinante Universo de Arduino, una plataforma de creación electrónica que te permite explorar y crear proyectos desde tu imaginación ...",
        imageUrl: "/arduino/arduino-sumergente-en-el-universo-de-la-creacion-electronica/images/joven-disenando-carrito-con-Arduino.webp",
        imageAlt: "Joven diseñando un carrito en la computadora sobre el escritorio.",
        link: "/arduino/arduino-sumergente-en-el-universo-de-la-creacion-electronica/",
    },  
];
