var frontendCardContent = [
    {
        keywords: "enlaces, enlace, HTML, CSS, diseño, web, guía, completa, creación, de, internos, externos, enlaces, correo electrónico, teléfono, usabilidad",
        title: "Navegando el Diseño Web: Guía Completa sobre Enlaces en HTML y CSS",
        description: "Descubre cómo crear enlaces impactantes en tu diseño web con nuestra guía completa sobre enlaces en HTML y CSS.",
        imageUrl: "/frontend/navegando-el-diseno-web-guia-completa-sobre-enlaces-en-html-y-css/images/desarrollador-desarrolladora-mirando-pantalla.jpg",
        imageAlt: "Desarrollador y desarrolladora mirando la pantalla, con expresiones concentradas mientras intentan solucionar un error en el código.",
        link: "/frontend/navegando-el-diseno-web-guia-completa-sobre-enlaces-en-html-y-css/",
    },
    {
        keywords: "css, clear, propiedad, cajas, flotantes, diseño, web, control, layout, flujo",
        title: "Entendiendo la Propiedad 'Clear' en CSS: Controla Tus Cajas Flotantes",
        description: "Sumérgete en el mundo de CSS y descubre el poder de la propiedad Clear. Aprende a dominar las cajas flotantes y evitar problemas comunes de diseño",
        imageUrl: "/frontend/entendiendo-la-propiedad-clear-en-css-controla-tus-cajas-flotantes/images/desarrolladores-discusion-propiedad-clear.jpg",
        imageAlt: "Hombre explicando algo de programación a una chica mientras ambos miran atentamente la pantalla del ordenador.",
        link: "/frontend/entendiendo-la-propiedad-clear-en-css-controla-tus-cajas-flotantes/",
    },
    {
        keywords: "tablas, html, crear, estructura, en, tabla, etiquetas, diseño, estilos, css",
        title: "¿Cómo crear una tabla en HTML?",
        description: "Adéntrate en el mundo del diseño web con este tutorial completo sobre cómo crear y estilizar tablas en HTML. Desde los fundamentos básicos hasta los estilos más avanzados con CSS.",
        imageUrl: "/frontend/como-crear-una-tabla-en-html/images/mujer-hombre-desarrolladores-discusion.jpg",
        imageAlt: "Dos desarrolladores colaborando, con la chica explicando algo",
        link: "/frontend/como-crear-una-tabla-en-html/",

    },
    {
        keywords: "CSS, variables, propiedades, personalizadas, diseño, web, programación, programacion, estilos, :root, custom, properties, desarrollo",
        title: "Variables en CSS: Un Vistazo a las Propiedades Personalizadas",
        description: "Explora el poder de las Propiedades Personalizadas en CSS y descubre cómo simplificar y optimizar tus estilos para un desarrollo web más ágil.",
        imageUrl: "/frontend/variables-en-css-un-vistazo-a-las-propiedades-personalizadas/images/css-variables-cover.jpg",
        imageAlt: "Desarrolladora programando en su PC de escritorio mientras trabaja con variables en CSS",
        link: "/frontend/variables-en-css-un-vistazo-a-las-propiedades-personalizadas/",
    },
    {
        keywords: "clip-path, clip, path, diseño, web, formas, creativas, CSS, tutorial, guía, personalización, clippy, design",
        title: "Introducción al Clip-Path: Dando Formas Creativas a Tu Página Web",
        description: "Descubre el poder del clip-path en el diseño web. Aprende a darle formas creativas y únicas a tus contenidos, desde círculos simples hasta polígonos complejos ...",
        imageUrl: "/frontend/introduccion-al-clip-path-dando-formas-creativas-a-tu-pagina-web/images/clip-path-tutorial-header.jpg",
        imageAlt: "Desarrolladora revisando líneas de código en su monitor y apuntando con un bolígrafo",
        link: "/frontend/introduccion-al-clip-path-dando-formas-creativas-a-tu-pagina-web/",
    },
    {
        keywords: "menú, menu, web, guía, guia, para, principiantes, diseño, web, construccion, creacion, de, menús, desarrollo, web, practicos",
        title: "Creación de un Menú Web: Guía Completa para Principiantes",
        description: "Sumérgete en nuestra guía paso a paso para crear un menú web cautivador. Ideal para principiantes, te guiaremos por los detalles del diseño y consejos prácticos.",
        imageUrl: "/frontend/creacion-de-un-menu-web-guia-completa-para-principiantes/images/creacion-menu-web-desarrolladores.jpg",
        imageAlt: "Mujer desarrolladora trabajando en código mientras un colega masculino observa la pantalla",
        link: "/frontend/creacion-de-un-menu-web-guia-completa-para-principiantes/",
    },
    {
        keywords: "columnas, column-count, column-gap, column-rule, web, estilos, diseño, responsivo, tutorial, css",
        title: "Creando Columnas Estilizadas en CSS: Una Guía Paso a Paso",
        description: "Explora el fascinante mundo de las columnas en CSS con nuestra nueva entrada. Descubre cómo hacer tu texto más legible y estéticamente agradable al dividirlo en columnas.",
        imageUrl: "/frontend/creando-columnas-estilizadas-en-css-una-guia-paso-a-paso/images/desarrollador-trabajando-en-columnas-css.jpg",
        imageAlt: "Desarrollador trabajando en un ordenador, creando columnas con CSS",
        link: "/frontend/creando-columnas-estilizadas-en-css-una-guia-paso-a-paso/",
    },
    {
        keywords: "object-fit, object, fit, CSS, adaptar, imágenes, diseño, responsive, contenido, visual, ajustar, tamaño, cover, fill, contain",
        title: "Domina la Propiedad object-fit en CSS",
        description: "Sumérgete dentro del CSS con object-fit y descubre cómo transformar tus imágenes. Aprende a ajustar y posicionar sin distorsiones. ¡Transforma tus diseños ahora!",
        imageUrl: "/frontend/domina-la-propiedad-object-fit-en-css/images/desarrollador-codificando-tarjeta-blog.jpg",
        imageAlt: "Desarrollador mirando a la cámara con una computadora detrás mostrando código en la pantalla.",
        link: "/frontend/domina-la-propiedad-object-fit-en-css/",
    },
    {
        keywords: "css, imágenes, imagenes, imagen, background, diseño, web, estilos, background-clip, background-size, background-position, responsive, design",
        title: "Dominando las Imágenes de Fondo en CSS: Guía Paso a Paso",
        description: "Sumérgete en el mundo del CSS y aprende a dominar las imágenes de fondo con nuestra guía completa. Desde lo básico hasta lo avanzado, ¡aquí lo encontrarás todo!",
        imageUrl: "/frontend/dominando-las-imagenes-de-fondo-en-css-guia-paso-a-paso/images/dominar-imagenes-fondo-css.jpg",
        imageAlt: "Desarrolladora sonriendo hacia la cámara con código en pantalla, acompañada de otro desarrollador enfocado en su trabajo.",
        link: "/frontend/dominando-las-imagenes-de-fondo-en-css-guia-paso-a-paso/",
    },
    {
        keywords: "cajas, flotantes, float, maquetación, web, diseño, responsivo, flexible, CSS, técnicas, avanzadas, estructura, de, página",
        title: "Cajas Flotantes: Un Vistazo a su Versatilidad en el Diseño Web",
        description: "Explora la magia de crear diseños responsivos con cajas flotantes en tu sitio web, gracias a un enfoque innovador de maquetación web en CSS...",
        imageUrl: "/frontend/cajas-flotantes-un-vistazo-a-su-versatilidad-en-el-diseno-web/images/Diseno-Responsivo-Con-Cajas-Flotantes.jpg",
        imageAlt: "Diseño Responsivo con Cajas Flotantes",
        link: "/frontend/cajas-flotantes-un-vistazo-a-su-versatilidad-en-el-diseno-web/",
    },
    {
        keywords: "flexbox, flex, contenido, flex-box, flexible, maquetación, web, diseño, responsivo, responsive, CSS, técnicas, avanzadas, flexible, adaptable",
        title: "¡Convierte tu Web en un Espacio Dinámico con Flexbox!",
        description: "Descubre cómo crear contenedores y elementos flexibles con Flexbox, una poderosa herramienta de CSS para el diseño web moderno ...",
        imageUrl: "/frontend/convierte-tu-web-en-un-espacio-dinamico-con-flexbox/images/Flexbox-Maquetado-Responsivo.jpg",
        imageAlt: "Cómo usar Flexbox para organizar elementos en CSS",
        link: "/frontend/convierte-tu-web-en-un-espacio-dinamico-con-flexbox/",
    },
    
];
