const frontendCardContent = [
    {
        keywords: "IndexedDB, leer, objetos, almacenamiento, puntero, almacén, puntero.value, método continue(), base, de, datos, puntero.target, lista, contactos, mostrar, actualizar, lista",
        title: "IndexedDB: Descubre cómo acceder y leer OBJETOS almacenados",
        description: "Descubre cómo utilizar IndexedDB para acceder, leer y gestionar los objetos almacenados en tu base de datos. Sumérgete en el mundo de las bases de datos del lado del cliente.",
        imageUrl: "/frontend/indexeddb-descubre-como-acceder-y-leer-objetos-almacenados/images/Desarrolladores-asombrados-indexeddb.webp",
        imageAlt: "Desarrolladores asombrados mirando resultados de IndexedDB.",
        link: "/frontend/indexeddb-descubre-como-acceder-y-leer-objetos-almacenados/",
    },
    {
        keywords: "IndexedDB, almacenar, objetos, base, de, datos, cliente, key, clave, objeto, almacén, índice, transacción, transacion, transaction, almacenamiento, web, operaciones, con, métodos, guardar, IDBDatabase, IDBTransaction, IDBObjectStore",
        title: "IndexedDB y el Arte de Almacenar Objetos: Todo lo que Necesitas Saber",
        description: "Aprende cómo almacenar objetos y desentraña las complejidades del almacenamiento en bases de datos del lado del cliente. ¡Descubre los secretos del IndexedDB y potencia tus habilidades en desarrollo web!",
        imageUrl: "/frontend/indexeddb-y-el-arte-de-almacenar-objetos-todo-lo-que-necesitas-saber/images/desarrollador-indexeddb-codigo.webp",
        imageAlt: "Desarrollador analizando código relacionado con IndexedDB en su computadora.",
        link: "/frontend/indexeddb-y-el-arte-de-almacenar-objetos-todo-lo-que-necesitas-saber/",
    },
    {
        keywords: "IndexedDB, Front-End, JavaScript, gestionar, Application tab, navegador, tutorial, abrir, Indexeddb, base, de, datos, crear, almacén, almacen",
        title: "¿Cómo crear una Base de Datos en el Front-End con IndexedDB y JavaScript?",
        description: "Descubre cómo crear y gestionar una base de datos directamente en el Front-End utilizando IndexedDB y JavaScript. Ideal para amantes del desarrollo web.",
        imageUrl: "/frontend/como-crear-una-base-de-datos-en-el-front-end-con-indexeddb-y-javascript/images/desarrolladoras-revisando-indexeddb-en-pantalla-y-movil.webp",
        imageAlt: "Dos desarrolladoras revisando el uso de IndexedDB en pantalla y móvil",
        link: "/frontend/como-crear-una-base-de-datos-en-el-front-end-con-indexeddb-y-javascript/",
    },
    {
        keywords: "almacenamiento web, local storage, session storage, javascript, guía, tutorial, introducción, persistencia de datos, guardar datos, acceder datos, borrar datos, storage en navegador, sessionStorage, localStorage, métodos storage, aprender storage, experiencia de usuario, optimización web, persistencia en web",
        title: "Dominando el Almacenamiento Web: Local Storage y Session Storage",
        description: "Sumérgete en el mundo del almacenamiento web con nuestra guía sobre Local Storage y Session Storage. Aprende cómo dominar estos poderosos herramientas de JavaScript y mejora la experiencia de usuario en tus proyectos.",
        imageUrl: "/frontend/dominando-el-almacenamiento-web-local-storage-y-session-storage/images/desarrollador-trabajando-local-session-storage.webp",
        imageAlt: "Desarrollador trabajando desde su casa, enfocado en el almacenamiento web con Local Storage y Session Storage",
        link: "/frontend/dominando-el-almacenamiento-web-local-storage-y-session-storage/",
    },
    {
        keywords: "slider, HTML, CSS, JavaScript, ícono derecha, ícono izquierda, transición, Margin Left, contador, querySelectorAll, Lista de Nodos, MoverDerecha, MoverIzquierda, MoverSlider, img-slider, código",
        title: "¿Cómo hacer un SLIDER con HTML, CSS y JavaScript?",
        description: "Descubre paso a paso cómo crear un slider dinámico y responsivo utilizando HTML, CSS y JavaScript. ¡Haz que tus imágenes cobren vida y mejora la interactividad de tu sitio con esta guía detallada!",
        imageUrl: "/frontend/como-hacer-un-slider-con-html-css-y-javascript/images/slider-con-html-css-javascript.webp",
        imageAlt: "Desarrollador concentrado mirando la pantalla, revisando el funcionamiento del slider que creó con HTML, CSS y JavaScript.",
        link: "/frontend/como-hacer-un-slider-con-html-css-y-javascript/",
    },
    {
        keywords: "slider, JavaScript, navegación de imágenes, interactividad, dinámica, MoverDerecha, MoverIzquierda, setInterval, event listeners, setTimeout, tutorial, guía, código",
        title: "¿Cómo hacer un Slider con JavaScript?",
        description: "Explora la magia detrás de la creación de sliders con JavaScript. En esta entrada, te guiaremos a través de los fundamentos de la navegación entre imágenes y cómo lograr una experiencia de usuario interactiva y dinámica.",
        imageUrl: "/frontend/como-hacer-un-slider-con-javascript/images/equipo-desarrollando-un-slider-con-javascript.webp",
        imageAlt: "Dos desarrolladores discutiendo detalles sobre la implementación de un slider con JavaScript frente a la pantalla de un ordenador.",
        link: "/frontend/como-hacer-un-slider-con-javascript/",
    },
    {
        keywords: "videos, en, HTML, personalizar, videos, atributo, autoplay, muted, reproducción, automática, bucle, de, video, loop, controles, video, controls, imagen, previa, poster, carga, preload, guía, tutorial",
        title: "Incorporando y Personalizando Videos en HTML: Una Guía Completa",
        description: "Descubre cómo incorporar y personalizar videos en HTML eficazmente. Desde formatos hasta controles, esta guía te lleva paso a paso hacia una experiencia web óptima.",
        imageUrl: "/frontend/incorporando-y-personalizando-videos-en-html-una-guia-completa/images/equipo-desarrolladores-aplicacion-web.webp",
        imageAlt: "Equipo de desarrolladores trabajando en una aplicación web, con dos miembros codificando activamente mientras otros discuten temas relacionados.",
        link: "/frontend/incorporando-y-personalizando-videos-en-html-una-guia-completa/",
    },
    {
        keywords: "Manipulación, del, DOM, Creación, de, elementos, HTML, Adición, JavaScript, dinámicos, innerHTML, Método forEach, Pintar, Técnicas, desarrollo, web, arrays, JS, eficiente, Generación, dinámica, contenidos, Ejemplos",
        title: "Manipulando el DOM: Creación y Adición de Elementos HTML con JavaScript",
        description: "Descubre cómo manipular el DOM con JavaScript de manera eficiente. En esta entrada, profundizamos en la creación y adición dinámica de elementos HTML, proporcionando ejemplos claros y técnicas prácticas.",
        imageUrl: "/frontend/manipulando-el-dom-creacion-y-adicion-de-elementos-html-con-javascript/images/desarrolladores-manipulacion-dom.webp",
        imageAlt: "Desarrollador y desarrolladora trabajando en la manipulación del DOM utilizando JavaScript",
        link: "/frontend/manipulando-el-dom-creacion-y-adicion-de-elementos-html-con-javascript/",
    },
    {
        keywords: "funciones, en, javascript, Comunicacion, entre, Ámbito, ambito, de, Renombrar, variables, Organización, organizacion, código, codigo Funciones declarativas, anónimas, anonimas, flecha, que, es, el, Hoisting, ECMAScript 6",
        title: "Descubre Cómo Mejorar la Comunicación Entre Funciones en JavaScript",
        description: "Aprende a mejorar la comunicación entre funciones en JavaScript para llevar tu código al siguiente nivel. Este tutorial te guiará a través de técnicas efectivas para escribir funciones más limpias y organizadas.",
        imageUrl: "/frontend/descubre-como-mejorar-la-comunicacion-entre-funciones-en-javascript/images/comunicacion-entre-funciones-javascrcript.webp",
        imageAlt: "Una pareja tumbada en cómodos sillones, la chica está escribiendo código mientras su pareja la observa; representando una buena comunicación entre funciones en JavaScript.",
        link: "/frontend/descubre-como-mejorar-la-comunicacion-entre-funciones-en-javascript/",
    },
    {
        keywords: "Fade, In, JavaScript, efecto, scroll, tutorial, guía, guia, paso a paso, animación, animacion, codigo, código, frontend, desarrollo web",
        title: "Crear un Efecto Fade In Asombroso en JavaScript: Todo lo que Necesitas Saber",
        description: "Aprende a crear un efecto Fade In asombroso usando JavaScript con nuestro tutorial detallado. Esta guía te llevará paso a paso a través del proceso para hacer que tu sitio web se destaque.",
        imageUrl: "/frontend/crear-un-efecto-fade-in-asombroso-en-javascript/images/hombre-codificando-efecto-fade-in-javascript.webp",
        imageAlt: "Hombre joven con audífonos sentado frente a una laptop, codificando un efecto Fade In en JavaScript.",
        link: "/frontend/crear-un-efecto-fade-in-asombroso-en-javascript/",
    },
    {
        keywords: "Efecto, de, Scroll, Desplazamiento, JavaScript, Menú, menu, Código, CSS, Propiedad, Cambiar, Color, de, fondo, window.onscroll, onscroll, efect",
        title: "¿Cómo hacer Efecto Scroll con JavaScript?",
        description: "Descubre cómo añadir un toque dinámico y atractivo a tu sitio web con efectos de desplazamiento (Scroll) en JavaScript. Sumérgete en este tutorial detallado que te guiará paso a paso para implementar un efecto de scroll en el menú de tu página.",
        imageUrl: "/frontend/como-hacer-efecto-scroll-con-javascript/images/chica-en-escritorio-trabajando-en-efecto-scroll.webp",
        imageAlt: "Chica sentada en su escritorio mirando el efecto de desplazamiento que ha implementado en su sitio web.",
        link: "/frontend/como-hacer-efecto-scroll-con-javascript/",
    },

    {
        keywords: "css, grid, galería, galeria, responsive, design, desarrollo, web, html, css, tutorial, guía, paso, a, media, queries, posicionamiento, layout, adaptabilidad, diseño, web, imágenes, imagenes",
        title: "Cómo Crear una Galería Responsive con CSS Grid: Guía Paso a Paso",
        description: "Descubre cómo crear una impresionante galería de imágenes responsive con CSS Grid. Esta guía paso a paso te lleva desde la estructura HTML básica hasta las media queries, asegurándote de que tu galería se vea genial en todos los dispositivos.",
        imageUrl: "/frontend/como-crear-una-galeria-responsive-con-css-grid-guia-paso-a-paso/images/galeria-responsive-css-grid.jpg",
        imageAlt: "Tres desarrolladores colaborando en un proyecto de galería de imágenes con CSS Grid: uno revisando el diseño en una tableta, mientras las otras dos discuten las adaptaciones para pantallas grandes y el código subyacente.",
        link: "/frontend/como-crear-una-galeria-responsive-con-css-grid-guia-paso-a-paso/",
    },
    {
        keywords: "HTML, CSS, JavaScript, menú, menu, desplegable, transición, transicion, ícono, icono, de, responsivo, adaptativo, tutorial, paso a paso, código, programación, rotación, línea",
        title: "Transición en el ícono del menú ¿Cómo hacerlo?",
        description: "Descubre cómo crear una transición suave en el ícono de tu menú desplegable con HTML, CSS y JavaScript. Sigue nuestro tutorial paso a paso y haz que tu menú sea no solo funcional sino también visualmente atractivo.",
        imageUrl: "/frontend/transicion-en-el-icono-del-menu-como-hacerlo/images/icono-menu-desplegable-javascript.jpg",
        imageAlt: "Dos muchachos discutiendo cómo hacer una transición en el ícono del menú desplegable usando HTML, CSS y JavaScript.",
        link: "/frontend/transicion-en-el-icono-del-menu-como-hacerlo/",
    },
    {
        keywords: "menú,com, hacer, un, menu, desplegable, con, html, css, desplegable,  javascript, tutorial, entrada, responsive, ocultar, mostrar, contenido",
        title: "Cómo hacer un menú desplegable con HTML, CSS y JavaScript?",
        description: "Dale vida a tu sitio web con un menú desplegable interactivo. En esta guía paso a paso, exploraremos cómo crear un menú desplegable adaptable utilizando HTML, CSS y JavaScript.",
        imageUrl: "/frontend/como-hacer-un-menu-desplegable-con-html-css-y-javascript/images/menu-desplegable-html-css-javascript.jpg",
        imageAlt: "Chica explorando el emocionante mundo del menú desplegable en su PC de escritorio: una guía completa de HTML, CSS y JavaScript para crear un menú interactivo y adaptable en AprendeCode.",
        link: "/frontend/como-hacer-un-menu-desplegable-con-html-css-y-javascript/",
    },
    {
        keywords: "como, ocultar, mostrar, contenido, con, javascript, NodeList, forEach, optimización, if-else, tutorial, entrada, blog, comentarios, testimonios",
        title: "¿Cómo ocultar y mostrar contenido con JavaScript?",
        description: "Descubre cómo ocultar y mostrar contenido con JavaScript de manera eficiente. Desde la preparación de tu HTML y CSS, hasta la implementación de Event Listeners y estructuras condicionales con if-else.",
        imageUrl: "/frontend/como-ocultar-y-mostrar-contenido-con-javascript/images/mujer-entendiendo-codigo-para-ocultar-mostrar-contenido-javascript.jpg",
        imageAlt: "Mujer analizando líneas de código en su computadora para ocultar y mostrar contenido con JavaScript",
        link: "/frontend/como-ocultar-y-mostrar-contenido-con-javascript/",
    },
    {
        keywords: "css grid, diseño, diseno, responsive, web, grids, retícula, diseño sin Media Queries, posicionamiento, layout, adaptable, tutorial, principiantes, avanzado, maquetación, estructura, web, desarrollo, columnas, filas",
        title: "CSS Grid desde Cero: Diseños Adaptables Sin Necesidad de Media Queries",
        description: "Descubre el poder del CSS Grid. Sumérgete en una guía completa, desde lo básico hasta conseguir diseños responsive. ¡No esperes más y amplía tus habilidades de diseño web!",
        imageUrl: "/frontend/css-grid-desde-cero-disenos-adaptables-sin-necesidad-de-media-queries/images/desarrollando-layout-css-grid.jpg",
        imageAlt: "Ilustración de un chico concentrado escribiendo en su laptop en un entorno de trabajo, destacando la implementación de CSS Grid para diseños adaptables en desarrollo web.",
        link: "/frontend/css-grid-desde-cero-disenos-adaptables-sin-necesidad-de-media-queries/",
    },
    {
        keywords: "media queries, diseño adaptativo, puntos de quiebre, max-width, min-width, Responsive design, CSS adaptativo, Dispositivos móviles, moviles, diseño fluido, transiciones estéticas",
        title: "Descubre las Media Queries: La Clave para un Diseño Web Responsivo",
        description: "¡Profundiza con nosotros en el fascinante mundo de las Media Queries! Descubre cómo transforman el diseño web y por qué son esenciales para tu viaje de aprendizaje.",
        imageUrl: "/frontend/descubre-las-media-queries-la-clave-para-un-diseno-web-responsivo/images/equipo-desarrolladores.jpg",
        imageAlt: "Equipo de desarrolladores trabajando en una mesa, con una chica explicando código a un chico a su lado",
        link: "/frontend/descubre-las-media-queries-la-clave-para-un-diseno-web-responsivo/",
    },
    {
        keywords: "enlaces, enlace, HTML, CSS, diseño, web, guía, completa, creación, de, internos, externos, enlaces, correo electrónico, teléfono, usabilidad",
        title: "Navegando el Diseño Web: Guía Completa sobre Enlaces en HTML y CSS",
        description: "Descubre cómo crear enlaces impactantes en tu diseño web con nuestra guía completa sobre enlaces en HTML y CSS.",
        imageUrl: "/frontend/navegando-el-diseno-web-guia-completa-sobre-enlaces-en-html-y-css/images/desarrollador-desarrolladora-mirando-pantalla.jpg",
        imageAlt: "Desarrollador y desarrolladora mirando la pantalla, con expresiones concentradas mientras intentan solucionar un error en el código.",
        link: "/frontend/navegando-el-diseno-web-guia-completa-sobre-enlaces-en-html-y-css/",
    },
    {
        keywords: "css, clear, propiedad, cajas, flotantes, diseño, web, control, layout, flujo",
        title: "Entendiendo la Propiedad 'Clear' en CSS: Controla Tus Cajas Flotantes",
        description: "Sumérgete en el mundo de CSS y descubre el poder de la propiedad Clear. Aprende a dominar las cajas flotantes y evitar problemas comunes de diseño",
        imageUrl: "/frontend/entendiendo-la-propiedad-clear-en-css-controla-tus-cajas-flotantes/images/desarrolladores-discusion-propiedad-clear.jpg",
        imageAlt: "Hombre explicando algo de programación a una chica mientras ambos miran atentamente la pantalla del ordenador.",
        link: "/frontend/entendiendo-la-propiedad-clear-en-css-controla-tus-cajas-flotantes/",
    },
    {
        keywords: "tablas, html, crear, estructura, en, tabla, etiquetas, diseño, estilos, css",
        title: "¿Cómo crear una tabla en HTML?",
        description: "Adéntrate en el mundo del diseño web con este tutorial completo sobre cómo crear y estilizar tablas en HTML. Desde los fundamentos básicos hasta los estilos más avanzados con CSS.",
        imageUrl: "/frontend/como-crear-una-tabla-en-html/images/mujer-hombre-desarrolladores-discusion.jpg",
        imageAlt: "Dos desarrolladores colaborando, con la chica explicando algo",
        link: "/frontend/como-crear-una-tabla-en-html/",

    },
    {
        keywords: "CSS, variables, propiedades, personalizadas, diseño, web, programación, programacion, estilos, :root, custom, properties, desarrollo",
        title: "Variables en CSS: Un Vistazo a las Propiedades Personalizadas",
        description: "Explora el poder de las Propiedades Personalizadas en CSS y descubre cómo simplificar y optimizar tus estilos para un desarrollo web más ágil.",
        imageUrl: "/frontend/variables-en-css-un-vistazo-a-las-propiedades-personalizadas/images/css-variables-cover.jpg",
        imageAlt: "Desarrolladora programando en su PC de escritorio mientras trabaja con variables en CSS",
        link: "/frontend/variables-en-css-un-vistazo-a-las-propiedades-personalizadas/",
    },
    {
        keywords: "clip-path, clip, path, diseño, web, formas, creativas, CSS, tutorial, guía, personalización, clippy, design",
        title: "Introducción al Clip-Path: Dando Formas Creativas a Tu Página Web",
        description: "Descubre el poder del clip-path en el diseño web. Aprende a darle formas creativas y únicas a tus contenidos, desde círculos simples hasta polígonos complejos ...",
        imageUrl: "/frontend/introduccion-al-clip-path-dando-formas-creativas-a-tu-pagina-web/images/clip-path-tutorial-header.jpg",
        imageAlt: "Desarrolladora revisando líneas de código en su monitor y apuntando con un bolígrafo",
        link: "/frontend/introduccion-al-clip-path-dando-formas-creativas-a-tu-pagina-web/",
    },
    {
        keywords: "menú, menu, web, guía, guia, para, principiantes, diseño, web, construccion, creacion, de, menús, desarrollo, web, practicos",
        title: "Creación de un Menú Web: Guía Completa para Principiantes",
        description: "Sumérgete en nuestra guía paso a paso para crear un menú web cautivador. Ideal para principiantes, te guiaremos por los detalles del diseño y consejos prácticos.",
        imageUrl: "/frontend/creacion-de-un-menu-web-guia-completa-para-principiantes/images/creacion-menu-web-desarrolladores.jpg",
        imageAlt: "Mujer desarrolladora trabajando en código mientras un colega masculino observa la pantalla",
        link: "/frontend/creacion-de-un-menu-web-guia-completa-para-principiantes/",
    },
    {
        keywords: "columnas, column-count, column-gap, column-rule, web, estilos, diseño, responsivo, tutorial, css",
        title: "Creando Columnas Estilizadas en CSS: Una Guía Paso a Paso",
        description: "Explora el fascinante mundo de las columnas en CSS con nuestra nueva entrada. Descubre cómo hacer tu texto más legible y estéticamente agradable al dividirlo en columnas.",
        imageUrl: "/frontend/creando-columnas-estilizadas-en-css-una-guia-paso-a-paso/images/desarrollador-trabajando-en-columnas-css.jpg",
        imageAlt: "Desarrollador trabajando en un ordenador, creando columnas con CSS",
        link: "/frontend/creando-columnas-estilizadas-en-css-una-guia-paso-a-paso/",
    },
    {
        keywords: "object-fit, object, fit, CSS, adaptar, imágenes, diseño, responsive, contenido, visual, ajustar, tamaño, cover, fill, contain",
        title: "Domina la Propiedad object-fit en CSS",
        description: "Sumérgete dentro del CSS con object-fit y descubre cómo transformar tus imágenes. Aprende a ajustar y posicionar sin distorsiones. ¡Transforma tus diseños ahora!",
        imageUrl: "/frontend/domina-la-propiedad-object-fit-en-css/images/desarrollador-codificando-tarjeta-blog.jpg",
        imageAlt: "Desarrollador mirando a la cámara con una computadora detrás mostrando código en la pantalla.",
        link: "/frontend/domina-la-propiedad-object-fit-en-css/",
    },
    {
        keywords: "css, imágenes, imagenes, imagen, background, diseño, web, estilos, background-clip, background-size, background-position, responsive, design",
        title: "Dominando las Imágenes de Fondo en CSS: Guía Paso a Paso",
        description: "Sumérgete en el mundo del CSS y aprende a dominar las imágenes de fondo con nuestra guía completa. Desde lo básico hasta lo avanzado, ¡aquí lo encontrarás todo!",
        imageUrl: "/frontend/dominando-las-imagenes-de-fondo-en-css-guia-paso-a-paso/images/dominar-imagenes-fondo-css.jpg",
        imageAlt: "Desarrolladora sonriendo hacia la cámara con código en pantalla, acompañada de otro desarrollador enfocado en su trabajo.",
        link: "/frontend/dominando-las-imagenes-de-fondo-en-css-guia-paso-a-paso/",
    },
    {
        keywords: "cajas, flotantes, float, maquetación, web, diseño, responsivo, flexible, CSS, técnicas, avanzadas, estructura, de, página",
        title: "Cajas Flotantes: Un Vistazo a su Versatilidad en el Diseño Web",
        description: "Explora la magia de crear diseños responsivos con cajas flotantes en tu sitio web, gracias a un enfoque innovador de maquetación web en CSS...",
        imageUrl: "/frontend/cajas-flotantes-un-vistazo-a-su-versatilidad-en-el-diseno-web/images/Diseno-Responsivo-Con-Cajas-Flotantes.jpg",
        imageAlt: "Diseño Responsivo con Cajas Flotantes",
        link: "/frontend/cajas-flotantes-un-vistazo-a-su-versatilidad-en-el-diseno-web/",
    },
    {
        keywords: "flexbox, flex, contenido, flex-box, flexible, maquetación, web, diseño, responsivo, responsive, CSS, técnicas, avanzadas, flexible, adaptable",
        title: "¡Convierte tu Web en un Espacio Dinámico con Flexbox!",
        description: "Descubre cómo crear contenedores y elementos flexibles con Flexbox, una poderosa herramienta de CSS para el diseño web moderno ...",
        imageUrl: "/frontend/convierte-tu-web-en-un-espacio-dinamico-con-flexbox/images/Flexbox-Maquetado-Responsivo.jpg",
        imageAlt: "Cómo usar Flexbox para organizar elementos en CSS",
        link: "/frontend/convierte-tu-web-en-un-espacio-dinamico-con-flexbox/",
    },

];
